apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-http-echo
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "http-echo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "http-echo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: http-echo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-text=hello world"
          ports:
            - containerPort: 5678